### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by Despaitre876** [mr-chibi/mmo#1]
It seems that your data package is currently only in English, can you support more languages if you can? For example, Chinese

**Comment by mr-chibi** [comment]
Let me see what I can do see if it's possible or not.
I don't think it's possible game doesn't support in code to auto translate.

I'm sorry, :(

**Comment by Despaitre876** [comment]
![17251033-quests-menu-e2950](https://github.com/mr-chibi/mmo/assets/136472967/256b9cb1-35f8-4cad-96fc-69e31b1035ce)
![17251029-gamerules](https://github.com/mr-chibi/mmo/assets/136472967/2722a976-7152-4f5c-9827-0b0ad57c9445)
![Uploading 17251032-menu.png…]()

I am referring to some translations of these texts

**Comment by mr-chibi** [comment]
Sorry, Minecraft doesn't have a support multiple languages :(
